### ISSUE TITLE
Sortable table columns

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/bootstrap-flask#107]
Provide a way to sort table columns. When used, the developer must indicate which column is sorted on and if the default sort is up or down. This is shown in the header with one of:
- https://icons.getbootstrap.com/icons/caret-down-fill/
- https://icons.getbootstrap.com/icons/caret-up-fill/

Unsorted columns do not have an icon. When another column header is selected, then that one will be sorted. With a second click, the sorting will be reversed.

Sorting will have to work together with pagination. Initially, no second sort will be supported.

**Comment by ziddey** [comment]
This is out of scope of bootstrap, but can be easily added with [datatables](https://datatables.net/examples/styling/bootstrap4.html)

**Comment by PanderMusubi** [comment]
Thanks

**Comment by PanderMusubi** [comment]
There is more functionality in bootstrap-flask which is not specifically Bootstrap. The solution you provided works but is a heavy one. As @greyli indicated this as a feature, I still would like to see a basic sort implemented on the tables here. Hence, reopening.

**Comment by greyli** [comment]
It will bring too much complexity, I think this should be supported with an external library.
