### ISSUE TITLE
Add to README.md how to run the tests

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/bootstrap-flask#170]
Please, add to README.md how to run the tests.

**Comment by greyli** [comment]
#171 just update the development section in the docs. I will add a contributing guide later.

**Comment by PanderMusubi** [comment]
Thanks. Add also at https://github.com/greyli/bootstrap-flask/blame/master/README.md#L25

    Install development version with:
    
    ```
    $ python setup.py install
    ```

**Comment by PanderMusubi** [comment]
Tests can be run with:
    ```
    $ pytest
    ```
    or for more verbose output and stop after first failure:
    ```
    $ pytest -vx
    ```
