### ISSUE TITLE
Question kwargs without value

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/bootstrap-flask#188]
A question for usage of kwargs, how to add a key without a value such as https://www.w3schools.com/tags/att_input_autofocus.asp Will add example usage to the example application when I have the answer.

**Comment by PanderMusubi** [comment]
Should this be done with `wtforms.fields.Flags` from https://wtforms.readthedocs.io/en/master/fields/ ?

**Comment by greyli** [comment]
Passing autofocus="autofocus" is the correct usage.

https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes
