### ISSUE TITLE
render_table and multiline

### ISSUE THREAD

**Issue by serensoner** [helloflask/bootstrap-flask#212]
hey there, i'm using render table with a field that sometimes has multilines (separated by `\n`, or possibly `<br />`. is there a way to show this as multilines using render_table? i tried `render_table(...)|safe` and `render_table(data, ..)|safe` but neither worked. any ideas?

**Comment by PanderMusubi** [comment]
@serensnoer, for you what would be using `self()` instead of `my_macro()`.

**Comment by PanderMusubi** [comment]
@serensoner see https://github.com/greyli/bootstrap-flask/pull/204 which offers safe for specific columns.

**Comment by greyli** [comment]
Implemented in #204.
