### ISSUE TITLE
Possibility to add/include date time picker?

### ISSUE THREAD

**Issue by devleaks** [helloflask/bootstrap-flask#219]
Hello,

How difficult would it be to add the following bootstrap datetime picker to bootstrap-flask?

Picker: https://tarruda.github.io/bootstrap-datetimepicker/
Now maintained here: https://github.com/Eonasdan/tempus-dominus

Thank you.

**Comment by ningen1** [comment]
I use it in combination with the boostrap-flask

tempus-dominus has too many configuration options and visual modes, i dont think its good idea to spend time to integrate it here.

**Comment by greyli** [comment]
I would agree with ningen1, it's better to manage the integration by yourself.

Closing now.
