### ISSUE TITLE
How to override bootstrap variables.

### ISSUE THREAD

**Issue by Guillaume-Tnk** [helloflask/bootstrap-flask#220]
Hi, 
It's probably simple but I can't figure what's the way to customize my theme with bootstrap-flask.
If for example, I want to redefine the color: "$primary", how I'm I suppose to do it?
I have been looking at https://getbootstrap.com/docs/5.1/customize/sass/
but since I don't have the @import "../node_modules/bootstrap/*, it will not work, or am I supposed to import the bootstrap files locally in parallel with using bootstrap-flask?

edit: 
I actually did just that, import bootstrap with npm and followed [this](https://getbootstrap.com/docs/5.1/customize/sass/) to override, it's working.
If this is the correct approach, disregard my question, if there's a better one please let me know, thank you.

**Comment by greyli** [comment]
This project is just a helper for rendering Bootstrap markup HTML in the Jinja template. Please refer to Bootstrap docs for issues like this, thanks.

**Comment by Guillaume-Tnk** [comment]
@greyli As I said in the edit, that's exactly what I did. At first, I was wondering if there was a defined way to do it inside bootstrap-flask.
