### ISSUE TITLE
Example menu bootstrap5 not expanding

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/bootstrap-flask#224]
Example menu bootstrap5 not expanding, see http://173.212.227.186/ and make the browser window small, e.g. half your screen size on a laptop. Clicking the menu button does not expand it. Reported for version 2.0.2

**Comment by yuxiaoy1** [comment]
There are minor differences between Bootstrap4 and Bootstrap5 of the nav button tag, I'll make a PR quickly to fix this.
