### ISSUE TITLE
disable wrapper div in form

### ISSUE THREAD

**Issue by foozzi** [helloflask/bootstrap-flask#232]
how to remove this wrap (mb-3):
![Снимок экрана от 2022-05-24 17-57-20](https://user-images.githubusercontent.com/1178208/170067143-9aacc10d-c436-4184-8ef6-bb939245e772.png)

```python
class AuthForm(FlaskForm):
	hash = StringField("", validators=[Length(8, 256)], 
		render_kw={"class": "me-2"})

	submit = SubmitField("Auth", 
		render_kw={"class": "btn-outline-success"})
```

```html
{{render_form(auth_form(), extra_classes="d-flex")}}
```

**Comment by greyli** [comment]
This div can't be removed, but you can set config `BOOTSTRAP_FORM_GROUP_CLASSES` to an empty string to make this an empty div.
