### ISSUE TITLE
render_table() without SQLAlchemy not working

### ISSUE THREAD

**Issue by vpathuis** [helloflask/bootstrap-flask#242]
For render_table(), the documentation states: data – An iterable of data objects to render. Can be dicts or class objects.
When I try using this macro on a simple test list, I get an error: `AttributeError: 'Item' object has no attribute '__table__'`. 
It seems that SQLAlchemy is supposed to supply objects with `__table__`. All examples I've found use SQLAlchemy.

This is the test list:
```
@dataclass
class Item:
    col1: int
    col2: str

testlist = [
        Item(1, '2'),
        Item(3, '4')
    ]
```
Is using SQLAlchemy a requirement? If so, is the documentation correct?

**Comment by PanderMusubi** [comment]
Please see https://github.com/helloflask/bootstrap-flask/pull/243

**Comment by vpathuis** [comment]
Works perfect! 
The issue was not in the data but in the titles, which I'd assumed optional. I missed this sentence:  _if not provided, will automatically detect on provided data, currently only support SQLAlchemy object._
Thanks a lot for reacting, and so quickly!

**Comment by vpathuis** [comment]
Could it be there is a similar simple solution for using the action buttons? When I use `show_actions = True `and add a model (class) and an edit_url, I get `jinja2.exceptions.UndefinedError: 'type object' has no attribute 'query'`.

**Comment by PanderMusubi** [comment]
Sounds like SQLAlchemy is needed for that, or you need your class to implement that. See base/table.html line 11.

**Comment by vpathuis** [comment]
Thnx for the suggestion. I'll consider my options :) Great work anyhow.
