### ISSUE TITLE
Upgrade to Bootstrap 5.2.2

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/bootstrap-flask#244]
Please upgrade to:
- Bootstrap 5.2.0
- Bootswatch 5.2.0
- Bootstrap Icons 1.9.0
- flask 2.2.2
- flask-wtf 1.0.1
- jinja2 3.1.2
- werkzeug 2.2.2

**Comment by PanderMusubi** [comment]
Any progress on this as Bootstrap and Bootswatch are already at version 5.2.2?

**Comment by PanderMusubi** [comment]
Bootstrap Icons are now at version 1.10

**Comment by greyli** [comment]
I'm happy to review a PR.

**Comment by PanderMusubi** [comment]
I will make one.

**Comment by PanderMusubi** [comment]
@greyli can you review and merge https://github.com/helloflask/bootstrap-flask/pull/255 which fixes an error in table examples and help making an upgrade for Bootswatch.

**Comment by PanderMusubi** [comment]
Using these libraries works:
- Werkzeug-2.2.2
- Flask-2.2.2
- WTForms-3.0.1
- SQLAlchemy-1.4.42
- Flask_WTF-1.0.1
- Flask_SQLAlchemy-3.0.2

Of course, the requirements should use the minimum versions of these packages.

**Comment by PanderMusubi** [comment]
This PR contains the upgrade of:
- Bootstrap 5.2.2
- Bootstrap Icons 1.9.1
- Bootswatch 5.2.2

https://github.com/helloflask/bootstrap-flask/pull/257

Test the icons extra good and also merge PR 255.
