### ISSUE TITLE
unexpected .DS_Store

### ISSUE THREAD

**Issue by lixxu** [helloflask/bootstrap-flask#260]
every folder has a .DS_Store which causes error when pyinstaller distributed file run
![image](https://user-images.githubusercontent.com/264487/200988786-e95a5b17-28bb-4b0d-b338-fe756bbb8db9.png)
![image](https://user-images.githubusercontent.com/264487/200989048-fcf4bcf3-a8fe-431e-9c70-02fdaa439886.png)

**Comment by PanderMusubi** [comment]
This fine is not in our repository nor in the distributed files. Most probably your (or somebody's macos) computer created this file. Just delete it.

**Comment by lixxu** [comment]
you can check the files on pypi (both tar.gz and whl files have these files).
![image](https://user-images.githubusercontent.com/264487/201049915-53372b68-b7b1-4b09-81b6-c95236606fc1.png)
![image](https://user-images.githubusercontent.com/264487/201050020-103cd89d-c9a1-416a-9e2c-67532e58ab57.png)

**Comment by PanderMusubi** [comment]
Thanks, we will look into this.

**Comment by greyli** [comment]
I just released 2.2.0, this should be fixed now. Please verify, thanks.
