### ISSUE TITLE
Bootswatch Theme stored locally in session cookies

### ISSUE THREAD

**Issue by mobone** [helloflask/bootstrap-flask#342]
This is more of a request than an issue. Wondering if there is an easy way to make the bootswatch theme local to the persons session cookies vs global for all users.

**Comment by PanderMusubi** [comment]
This should be possible. Also via [flask-login](https://pypi.org/project/Flask-Login/) you can store it in a user profile. How exactly, I also have to figure out. If you have some answers, please share them here.

**Comment by PanderMusubi** [comment]
@mobone, can this issue be closed?

**Comment by greyli** [comment]
You can just implement this by yourself. Here is an example:

* Set the theme name and store to cookie: https://github.com/greyli/bluelog/blob/master/bluelog/blueprints/blog.py#L99-L106
* Load the CCS file based on the theme name in the cookie: https://github.com/greyli/bluelog/blob/master/bluelog/templates/base.html#L11

**Comment by PanderMusubi** [comment]
Probably more people will find this information useful. @greyli would it be interesting to add an implementation for it to https://github.com/helloflask/bootstrap-flask/blob/master/examples/bootstrap5/templates/bootswatch.html ? Because now, when somebody changes the Bootswatch theme, it changes for all users.

**Comment by greyli** [comment]
Sounds good! Could you help to submit a PR for it?

**Comment by PanderMusubi** [comment]
@mobone would you like to have a go at a PR?

**Comment by mobone** [comment]
Yes I would. When I was testing it I saw the same. I assume because the
theme is set in the backend it changes for all users.

**Comment by PanderMusubi** [comment]
Yes, that is the case now, but you can make it a user selection in a cookie. I can also share you some code to switch Bootstrap light and dark theme.

**Comment by PanderMusubi** [comment]
Yes, please make a PR :-)
