### ISSUE TITLE
TemplateNotFound jinja2.exceptions.TemplateNotFound: bootstrap/nav.html

### ISSUE THREAD

**Issue by aammjian** [helloflask/bootstrap-flask#94]
jinja2.exceptions.TemplateNotFound: bootstrap/nav.html

**Comment by greyli** [comment]
Hi, please make sure you have already installed this extension:

```
$ pip install bootstrap-flask
```

Besides, this extension can't use with Flask-Bootstrap at the same time, you may need to do this:

```
$ pip uninstall bootstrap-flask flask-bootstrap
$ pip install bootstrap-flask
```

**Comment by aammjian** [comment]
ok，tks.

**Comment by greyli** [comment]
TODO: Create a FAQ section in docs and add this issue.
